[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ffi = true
# solc = "0.5.16"

fs_permissions = [
    { access = "read", path = "./test/mocks/Owned2StepWrappers.huff" },
    { access = "read", path = "./test/mocks/BitMathWrappers.huff" }
]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "foundry-huff/=lib/foundry-huff/src/",
    "huffmate/=lib/huffmate/src/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config